connectors:
-
  connector_id: "Mk6mQ4sBezrCBhgAT3Ix"
  service_type: "google_drive"
  api_key: "TTA2bVE0c0JlenJDQmhnQWlISWo6dG9wS3hHTFdTcEdtVVdrcmN5UDUwUQ=="
elasticsearch:
  host: "https://2d67c95109654a08b761bcd0b88c4e8e.us-central1.gcp.cloud.es.io:443"
  api_key: "TTA2bVE0c0JlenJDQmhnQWlISWo6dG9wS3hHTFdTcEdtVVdrcmN5UDUwUQ=="
